name: myfood
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - gunicorn
  - sqlalchemy
  - psycopg2
  - email-validator
  - orjson
  - pydantic
  - typer
  - httpx
  - jinja2
  - click
  - pip
  - setuptools
