name: myfood
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - uvicorn
  - ujson
  - tk
  - sqlalchemy
  - readline
  - pydantic-core
  - psycopg2
  - orjson
  - openssl
  - ncurses
  - markupsafe
  - libzlib
  - libsqlite
  - libpq
  - libffi
  - libexpat
  - libedit
  - libcxx
  - krb5
  - gunicorn
  - greenlet
  - ca-certificates
  - bzip2
